#!/usr/bin/env bash

# Error codes + association:
# 1 - Running as root
# 2 - Unsupported platform
# 3 - Dependency issue
# 4 - Unsupported shell
# 5 - Setting $THEOS failed
# 6 - Theos clone failed
# 7 - Toolchain install failed
# 8 - SDK install failed
# 9 - Checkra1n '/opt' setup failed
# 10 - fakeroot adjustment failed
# 11 - Enabling Linux binary compat on FreeBSD failed

set -e

# Pretty print
special() {
	printf "\e[0;34m==> \e[1;34mTheos Installer:\e[m %s\n" "$1"
	printf "\e[0;34m==> \e[1;34mPatched by Krutifulmen (github)\e[m \n"
}

update() {
	printf "\n\e[0;36m==> \e[1;36m%s\e[m\n" "$1"
}

common() {
	printf "\n\e[0;37m==> \e[1;37m%s\e[m\n" "$1"
}

error() {
	printf "\e[0;31m==> \e[1;31m%s\m\n" "$1"
}


# Root is no bueno
if [[ $EUID -eq 0 ]]; then
	error "Theos should NOT be installed with or run as root (su/sudo)!"
	error "  - Please re-run the installer as a non-root user."
	exit 1
fi


# Common vars
PLATFORM=$(uname)
ARCH=$(uname -m)
CSHELL="${SHELL##*/}"
SHELL_ENV="unknown"
if [[ $CSHELL == sh || $CSHELL == bash || $CSHELL == dash ]]; then
	# Bash prioritizes bashrc > bash_profile > profile
	if [[ -f $HOME/.bashrc ]]; then
		SHELL_ENV="$HOME/.bashrc"
	elif [[ -f $HOME/.bash_profile ]]; then
		SHELL_ENV="$HOME/.bash_profile"
	else
		SHELL_ENV="$HOME/.profile"
	fi
elif [[ $CSHELL == zsh ]]; then
	# Zsh prioritizes zshenv > zprofile > zshrc
	zdot="${ZDOTDIR:-$HOME}"
	if [[ -f $zdot/.zshenv ]]; then
		SHELL_ENV="$zdot/.zshenv"
	elif [[ -f $zdot/.zprofile ]]; then
		SHELL_ENV="$zdot/.zprofile"
	else
		SHELL_ENV="$zdot/.zshrc"
	fi
fi


# The work
theos_bool() {
	AFFIRMATIVE=(Y y YES yes TRUE true)
	if [[ ${AFFIRMATIVE[*]} =~ $1 ]]; then
		return 0
	else
		return 1
	fi
}

set_theos() {
	# Check for $THEOS env var
	update "Checking for \$THEOS environment variable..."
	if ! [[ -z $THEOS ]]; then
		update "\$THEOS is already set to '$THEOS'. Nothing to do here."
	else
		update "\$THEOS has not been set. Setting now..."

		if [[ $SHELL_ENV == unknown ]]; then
			error "Current shell ($CSHELL) is unsupported by this installer. Please set the THEOS environment variable to '~/theos' manually before proceeding."
			exit 4
		fi

		# Set $THEOS
		if [[ $PLATFORM == Darwin && ! -x $(command -v xcode-select) && -f /.bootstrapped ]]; then
			echo "export THEOS=/opt/theos" >> "$SHELL_ENV"
			export THEOS=/opt/theos
			if [[ -d /opt ]]; then
				update "'/opt' already exists. Checking its ownership..."
				OWNER="$(stat -c '%U' /opt)"
				if [[ $OWNER == root ]]; then
					update "Owner of '/opt' is root. Attempting to switch owner to mobile..."
					sudo chown mobile /opt \
						&& update "Owner of '/opt' successfully transfered to mobile from root!" \
						|| (error "Failed to transfer ownership of '/opt' to mobile from root. Please see the log above."; exit 9)
				else
					update "Owner of '/opt' is not root. We should be good to go!"
				fi
			else
				update "Creating a special directory to house Theos..."
				sudo install -d -o mobile -g mobile /opt \
					&& update "Special directory for Theos created successfully!" \
					|| (error "Special directory create command seems to have encountered an error. Please see the log above."; exit 9)
			fi
		else
			echo "export THEOS=~/theos" >> "$SHELL_ENV"
			export THEOS=~/theos
		fi
	fi
}

get_theos() {
	# Get Theos
	update "Checking for Theos install..."
	if [[ -d $THEOS && $(ls -A "$THEOS") ]]; then
		update "Theos appears to already be installed. Checking for updates..."
		$THEOS/bin/update-theos
	else
		update "Theos does not appear to be installed. Cloning now..."
		git clone --recursive https://github.com/theos/theos.git $THEOS \
			&& update "Git clone of Theos was successful!" \
			|| (error "Theos git clone command seems to have encountered an error. Please see the log above."; exit 6)
	fi
}

get_sdks() {
	# Get patched sdks
	update "Checking for patched SDKs..."
	if [[ -d $THEOS/sdks/ && $(ls -A "$THEOS/sdks/" | grep sdk) ]]; then
		update "SDKs appear to already be installed."
	else
		update "SDKs do not appear to be installed. Installing now..."
		$THEOS/bin/install-sdk latest && $THEOS/bin/install-sdk latest-tv
		if ! [[ -z $(ls -A "$THEOS/sdks/" | grep sdk) ]]; then
			update "SDKs successfully installed!"
		else
			error "Something appears to have gone wrong. Please try again."
			exit 8
		fi
	fi
}

darwin() {
	XCODE="$(xcode-select -p)"
	if [[ $XCODE == /Library/Developer/CommandLineTools && ! -d /Applications/Xcode.app/Contents/Developer/ ]]; then
		error "Xcode, not just the Command Line Tools, is required for Theos to function properly. Please install Xcode before continuing with the installation."
		exit 3
	elif [[ $XCODE == /Library/Developer/CommandLineTools && -d /Applications/Xcode.app/Contents/Developer/ ]]; then
		sudo xcode-select -s /Applications/Xcode.app/Contents/Developer/
	elif [[ $XCODE != *.app/Contents/Developer ]]; then
		error "Xcode is required for Theos to function properly. Please install Xcode before continuing with the installation."
		exit 3
	fi

	update "Preparing to install dependencies..."
	if [[ -x $(command -v apt) && -f /opt/procursus/.procursus_strapped ]]; then
		sudo apt update || true
		sudo apt install -y ldid xz-utils \
			&& update "Dependencies have been successfully installed!" \
			|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
	elif [[ -x $(command -v port) ]]; then
		sudo port selfupdate || true
		yes | sudo port install ldid xz \
			&& update "Dependencies have been successfully installed!" \
			|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
	elif [[ -x $(command -v brew) ]]; then
		brew update || true
		brew install ldid xz \
			&& update "Dependencies have been successfully installed!" \
			|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
	fi

	set_theos
	get_theos
	get_sdks
}

darwin_mobile() {
	LEGACY=0
	KERNEL_VER=$(sysctl kern.osrelease | sed 's/[^0-9]*//g')
	if [[ $KERNEL_VER < 1800 ]]; then
		LEGACY=1
	fi

	if ! [[ -x $(command -v sudo) ]]; then
		error "Please install 'sudo' in your package manager before proceeding with the installation."
		exit 3
	fi
	if ! [[ -x $(command -v head) ]]; then
		error "Please install 'coreutils' in your package manager before proceeding with the installation."
		exit 3
	fi
	if ! [[ -x $(command -v xz) ]]; then
		error "Please install 'xz-utils' in your package manager before proceeding with the installation."
		exit 3
	fi
	if ! [[ -x $(command -v apt-get) ]]; then
		error "Please install 'apt' in your package manager before proceeding with the installation."
		exit 3
	fi

	APTVER="$(apt-get --version | head -n1 | cut -d' ' -f2)"
	if dpkg --compare-versions $APTVER ge 1.1; then
		uFLAGS=(--allow-insecure-repositories)
		iFLAGS=(--allow-unauthenticated --allow-downgrades)
	else
		uFLAGS=()
		iFLAGS=()
	fi

	update "Preparing to install dependencies. Please enter your password if prompted:"
	if [[ $LEGACY -eq 1 ]]; then
		sudo apt-get update "${uFLAGS[@]}" || true
		sudo apt-get install -y "${iFLAGS[@]}" org.theos.dependencies \
			&& update "Dependencies have been successfully installed!" \
			|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
	else
		if [[ -f /.procursus_strapped || -f /var/jb/.procursus_strapped ]]; then
			sudo apt update "${uFLAGS[@]}" || true
			sudo apt install -y "${iFLAGS[@]}" theos-dependencies \
				&& update "Dependencies have been successfully installed!" \
				|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
		else
			sudo apt update "${uFLAGS[@]}" || true
			sudo apt install -y "${iFLAGS[@]}" ca-certificates clang coreutils curl dpkg git grep ldid make odcctools perl com.bingner.plutil rsync xz \
				&& update "Dependencies have been successfully installed!" \
				|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
		fi
	fi

	set_theos
	get_theos
	get_sdks
}

linux() {
	DISTRO="unknown"
	if [[ -x $(command -v apt) ]]; then
		DISTRO="debian"
	elif [[ -x $(command -v pacman) ]]; then
		DISTRO="arch"
	elif [[ -x $(command -v dnf) ]]; then
		DISTRO="redhat"
	elif [[ -x $(command -v zypper) ]]; then
		DISTRO="suse"
	fi

	if ! [[ -x $(command -v sudo) ]]; then
		error "Please install 'sudo' before proceeding with the installation."
		exit 3
	fi

	update "Preparing to install dependencies. Please enter your password if prompted:"
	case $DISTRO in
		debian)
			sudo apt update || true
			# Вот тут изменен либмил2 на либмил2-утилс
			sudo apt install -y build-essential fakeroot rsync curl perl zip git libxml2-utils libssl-dev \
				&& update "Dependencies have been successfully installed!" \
				|| (error "Dependency install command seems to have encountered an error. Please see the log above."; exit 3)
			;;
		arch)
			sudo pacman -Syu || true
			sudo pacman -S --needed --noconfirm base-devel libbsd fakeroot openssl rsync curl perl zip git libxml2-utils \
				&& update "Dependencies have been successfully installed!" \
				|| (error "Dependencies have been successfully installed!"; exit 3)
			;;
		redhat)
			sudo dnf group install -y "c-development" --refresh \
				|| (error "Dependency install command failed."; exit 3)
			sudo dnf install -y fakeroot lzma libbsd rsync curl perl zip git libxml2-utils \
				&& update "Other dependencies have been successfully installed!" \
				|| (error "Other dependency install command failed."; exit 3)
			;;
		suse)
			sudo zypper refresh || true
			sudo zypper install -y -t pattern devel_basis \
				|| (error "Dependency install command failed."; exit 3)
			sudo zypper install -y fakeroot libbsd0 rsync curl perl zip git libxml2-utils \
				&& update "Other dependencies have been successfully installed!" \
				|| (error "Other dependency install command failed."; exit 3)
			;;
		*)
			error "Unsupported distribution."
			exit 3
			;;
	esac

	update "Adjusting fakeroot to favor sysv > tcp..."
	sudo update-alternatives --set fakeroot /usr/bin/fakeroot-sysv \
		&& update "fakeroot adjusted!" \
		|| (error "fakeroot adjustment failed."; exit 10)

	update "Checking for WSL..."
	rel="$(uname -r)"
	if [[ ${rel,,} =~ microsoft ]]; then
		if ! [[ $rel =~ WSL2 ]]; then
			update "WSL1! Need to adjust fakeroot as no sysv..."
			sudo update-alternatives --set fakeroot /usr/bin/fakeroot-tcp \
				&& update "fakeroot adjusted!" \
				|| (error "fakeroot adjustment failed."; exit 10)
		else
			update "WSL2! Nothing to do here."
		fi
	fi

	set_theos
	get_theos

	update "Checking for iOS toolchain..."
	if [[ -d $THEOS/toolchain/linux/iphone/ && $(ls -A "$THEOS/toolchain/linux/iphone") ]]; then
		update "A toolchain appears to already be installed."
	else
		update "A toolchain does not appear to be installed. Installing automatically..."
		sudo apt install -y libtinfo6
		if [[ $ARCH == aarch64 || $ARCH == x86_64 ]]; then
			curl -sL https://github.com/L1ghtmann/llvm-project/releases/latest/download/iOSToolchain-$ARCH.tar.xz | tar -xJvf - -C $THEOS/toolchain/
		else
			error "Apologies, we do not currently provide precompiled toolchains for $ARCH Linux."
			exit 7
		fi

		if [[ -x $THEOS/toolchain/linux/iphone/bin/clang ]]; then
			update "Successfully installed the toolchain!"
		else
			error "Something appears to have gone wrong -- the toolchain is not accessible."
			exit 7
		fi
	fi

	get_sdks
}

special "Starting install..."
common "Platform: $PLATFORM"
if [[ $PLATFORM == Darwin ]]; then
	if [[ -x $(command -v xcode-select) ]]; then
		darwin
	else
		darwin_mobile
	fi
elif [[ ${PLATFORM,,} == linux ]]; then
	linux
else
	error "'$PLATFORM' is currently unsupported by this installer and/or Theos."
	exit 2
fi

special "Theos has been successfully installed! Restart your shell and enjoy."
