#!/usr/bin/env bash

# Error codes + association:
# 1 - Running as root
# 2 - Unsupported platform
# 3 - Dependency issue
# 4 - Unsupported shell
# 5 - Setting $THEOS failed
# 6 - Theos clone failed
# 7 - Toolchain install failed
# 8 - SDK install failed
# 10 - fakeroot adjustment failed

set -e

# Pretty print
special() {
	printf "\e[0;34m==> \e[1;34mTheos Installer:\e[m %s\n" "$1"
	printf "\e[0;34m==> \e[1;34mPatched by Krutifulmen (github)\e[m \n"
}

update() {
	printf "\n\e[0;36m==> \e[1;36m%s\e[m\n" "$1"
}

common() {
	printf "\n\e[0;37m==> \e[1;37m%s\e[m\n" "$1"
}

error() {
	printf "\e[0;31m==> \e[1;31m%s\e[m\n" "$1"
}


# Root is no bueno
if [[ $EUID -eq 0 ]]; then
	error "Theos should NOT be installed with or run as root (su/sudo)!"
	error "  - Please re-run the installer as a non-root user."
	exit 1
fi


# Common vars
PLATFORM=$(uname)
ARCH=$(uname -m)
CSHELL="${SHELL##*/}"
SHELL_ENV="unknown"
if [[ $CSHELL == sh || $CSHELL == bash || $CSHELL == dash ]]; then
	if [[ -f $HOME/.bashrc ]]; then
		SHELL_ENV="$HOME/.bashrc"
	elif [[ -f $HOME/.bash_profile ]]; then
		SHELL_ENV="$HOME/.bash_profile"
	else
		SHELL_ENV="$HOME/.profile"
	fi
elif [[ $CSHELL == zsh ]]; then
	zdot="${ZDOTDIR:-$HOME}"
	if [[ -f $zdot/.zshenv ]]; then
		SHELL_ENV="$zdot/.zshenv"
	elif [[ -f $zdot/.zprofile ]]; then
		SHELL_ENV="$zdot/.zprofile"
	else
		SHELL_ENV="$zdot/.zshrc"
	fi
fi


# The work
theos_bool() {
	AFFIRMATIVE=(Y y YES yes TRUE true)
	if [[ ${AFFIRMATIVE[*]} =~ $1 ]]; then
		return 0
	else
		return 1
	fi
}

set_theos() {
	update "Checking for \$THEOS environment variable..."
	if ! [[ -z $THEOS ]]; then
		update "\$THEOS is already set to '$THEOS'. Nothing to do here."
	else
		update "\$THEOS has not been set. Setting now..."

		if [[ $SHELL_ENV == unknown ]]; then
			error "Current shell ($CSHELL) is unsupported. Set \$THEOS manually."
			exit 4
		fi

		echo "export THEOS=~/theos" >> "$SHELL_ENV"
		export THEOS=~/theos
	fi
}

get_theos() {
	update "Checking for Theos install..."
	if [[ -d $THEOS && $(ls -A "$THEOS") ]]; then
		update "Theos appears to already be installed. Checking for updates..."
		$THEOS/bin/update-theos || true
	else
		update "Theos does not appear to be installed. Cloning now..."
		git clone --recursive https://github.com/theos/theos.git $THEOS \
			&& update "Git clone of Theos was successful!" \
			|| (error "Theos git clone command failed."; exit 6)
	fi
}

# ПРАВИЛЬНЫЙ СКРИПТ: Тянет напрямую репозиторий со всеми SDK без участия API GitHub
get_sdks() {
	update "Checking for patched SDKs..."
	if [[ -d $THEOS/sdks/ && $(ls -A "$THEOS/sdks/" | grep sdk) ]]; then
		update "SDKs appear to already be installed."
	else
		update "SDKs do not appear to be installed. Cloning directly from GitHub repository..."
		rm -rf $THEOS/sdks
		git clone https://github.com/theos/sdks.git $THEOS/sdks \
			&& update "SDKs successfully installed!" \
			|| (error "Failed to clone SDKs repository."; exit 8)
	fi
}

darwin() {
	XCODE="$(xcode-select -p)"
	if [[ $XCODE == /Library/Developer/CommandLineTools && ! -d /Applications/Xcode.app/Contents/Developer/ ]]; then
		error "Xcode is required for Theos to function properly."
		exit 3
	fi

	update "Preparing to install dependencies..."
	if [[ -x $(command -v brew) ]]; then
		brew update || true
		brew install ldid xz
	fi

	set_theos
	get_theos
	get_sdks
}

darwin_mobile() {
	if ! [[ -x $(command -v sudo) ]]; then
		error "Please install 'sudo' before proceeding."
		exit 3
	fi

	update "Preparing to install dependencies..."
	sudo apt update || true
	sudo apt install -y ca-certificates clang coreutils curl dpkg git grep ldid make rsync xz

	set_theos
	get_theos
	get_sdks
}

linux() {
	DISTRO="unknown"
	if [[ -x $(command -v apt) ]]; then
		DISTRO="debian"
	elif [[ -x $(command -v pacman) ]]; then
		DISTRO="arch"
	elif [[ -x $(command -v dnf) ]]; then
		DISTRO="redhat"
	elif [[ -x $(command -v zypper) ]]; then
		DISTRO="suse"
	fi

	if ! [[ -x $(command -v sudo) ]]; then
		error "Please install 'sudo' before proceeding."
		exit 3
	fi

	update "Preparing to install dependencies..."
	case $DISTRO in
		debian)
			sudo apt update || true
			sudo apt install -y build-essential fakeroot rsync curl perl zip git libxml2-utils libssl-dev \
				&& update "Dependencies have been successfully installed!" \
				|| (error "Dependency install command failed."; exit 3)
			;;
		arch)
			sudo pacman -Syu || true
			sudo pacman -S --needed --noconfirm base-devel libbsd fakeroot openssl rsync curl perl zip git libxml2-utils \
				&& update "Dependencies have been successfully installed!" \
				|| (error "Dependency install command failed."; exit 3)
			;;
		*)
			error "Unsupported distribution for automatic dependency install."
			exit 3
			;;
	esac

	update "Adjusting fakeroot to favor sysv > tcp..."
	sudo update-alternatives --set fakeroot /usr/bin/fakeroot-sysv || true

	set_theos
	get_theos

	update "Checking for iOS toolchain..."
	if [[ -d $THEOS/toolchain/linux/iphone/ && $(ls -A "$THEOS/toolchain/linux/iphone") ]]; then
		update "A toolchain appears to already be installed."
	else
		update "A toolchain does not appear to be installed. Installing toolchain..."
		sudo apt install -y libtinfo6 || true
		mkdir -p $THEOS/toolchain
		if [[ $ARCH == aarch64 || $ARCH == x86_64 ]]; then
			curl -sL https://github.com/L1ghtmann/llvm-project/releases/latest/download/iOSToolchain-$ARCH.tar.xz | tar -xJvf - -C $THEOS/toolchain/
		else
			error "Unsupported architecture: $ARCH"
			exit 7
		fi

		if [[ -x $THEOS/toolchain/linux/iphone/bin/clang ]]; then
			update "Successfully installed the toolchain!"
		else
			error "Toolchain is not accessible."
			exit 7
		fi
	fi

	# Тут был баг оригинального кода (лишний get_sdks). Теперь управление передано общему вызову в конце.
}

special "Starting install..."
common "Platform: $PLATFORM"
if [[ $PLATFORM == Darwin ]]; then
	if [[ -x $(command -v xcode-select) ]]; then
		darwin
	else
		darwin_mobile
	fi
elif [[ ${PLATFORM,,} == linux ]]; then
	linux
	get_sdks
else
	error "'$PLATFORM' is currently unsupported."
	exit 2
fi

special "Theos has been successfully installed! This installer was patched by Krutifulmen xD"
